# inherit_from: .rubocop_todo.yml
AllCops:
  Exclude:
    - 'spec/test_app/*'
Metrics/LineLength:
  Max: 150
  Exclude:
    - 'spec/**/*'
Lint/DuplicatedKey:
  Exclude:
    - 'spec/controller/filter_spec.rb'
Metrics/BlockLength:
  CountComments: false
  Exclude:
    - 'json_api_server.gemspec'
    - 'spec/**/*'
Lint/UselessComparison:
  Exclude:
    - 'spec/json_api_server/attributes_builder_spec.rb'
    - 'spec/json_api_server/relationships_builder_spec.rb'
Style/Documentation:
  Exclude:
    - 'spec/**/*'
Metrics/CyclomaticComplexity:
  Max: 9
Metrics/AbcSize:
  Max: 25
Style/GuardClause:
  Exclude:
    - 'lib/json_api_server/filter_builders.rb'
    - 'lib/json_api_server/pagination.rb'
    - 'lib/json_api_server/relationships_builder.rb'
    - 'lib/json_api_server/validation_errors.rb'
Metrics/MethodLength:
  Max: 20
